// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_-rjgJkC7fiv1zWaBYLx4JUp-JNbJlE',
    appId: '1:381779685536:web:d31cbbad6d1f301d9b59c5',
    messagingSenderId: '381779685536',
    projectId: 'rsforms-6e943',
    authDomain: 'rsforms-6e943.firebaseapp.com',
    storageBucket: 'rsforms-6e943.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHODaRXw3IrA1xL3d36Wl_KKy7-txQjw',
    appId: '1:381779685536:android:0c21ce5cea6f008c9b59c5',
    messagingSenderId: '381779685536',
    projectId: 'rsforms-6e943',
    storageBucket: 'rsforms-6e943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6_pxdsCSRVT-fi_rLxFoAWSOED-uyJw',
    appId: '1:381779685536:ios:3f9122dcdf7fb28d9b59c5',
    messagingSenderId: '381779685536',
    projectId: 'rsforms-6e943',
    storageBucket: 'rsforms-6e943.appspot.com',
    iosClientId: '381779685536-llt839i9mpo7949ij2ei6t9k8jqgdor3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsforms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk6_pxdsCSRVT-fi_rLxFoAWSOED-uyJw',
    appId: '1:381779685536:ios:490adb94a5a49c7b9b59c5',
    messagingSenderId: '381779685536',
    projectId: 'rsforms-6e943',
    storageBucket: 'rsforms-6e943.appspot.com',
    iosClientId: '381779685536-vq06ujin24jf6207fbpjs673986ne81r.apps.googleusercontent.com',
    iosBundleId: 'com.example.rsforms.RunnerTests',
  );
}
